profile:
  name: "default"
  description: "Baseline build using common plans and local Chicago systems."
  include:
    paths:
      - "ssrf/plans/US/gmrs/*.yml"
      - "ssrf/plans/EU/pmr446/*.yml"
      - "ssrf/plans/US/amateur/*.yml"
      - "ssrf/plans/US/murs/*.yml"
      - "ssrf/plans/US/marine/*.yml"
      - "ssrf/plans/US/business/*.yml"
      - "ssrf/plans/US/weather/*.yml"
      - "ssrf/plans/US/rail/*.yml"
      - "ssrf/systems/US/IL/Cook/Chicago/**/*.yml"
      - "ssrf/systems/US/IL/Cook/_Countywide/**/*.yml"
      - "ssrf/systems/US/IL/_Statewide/**/*.yml"
      - "ssrf/systems/custom/*.yml"
    services: [] # optional filter; empty means no filter
  policy:
    files:
      - "policies/default.yml"
      - "policies/gmrs_channels.yml"
      - "policies/chicago_gmrs_repeaters.yml"
      - "policies/family_channels.yml"
      - "policies/pmr446.yml"
      - "policies/business_itinerant.yml"
      - "policies/chicago_businesses_northside.yml"
      - "policies/venues_chicago.yml"
      - "policies/rosehill_cemetery_dmr.yml"
      - "policies/wcars.yml"
      - "policies/marine_vhf.yml"
      - "policies/murs.yml"
      - "policies/rail_aar_scan.yml"
      - "policies/noaa_weather.yml"
      - "policies/chicagoland_dmr.yml"
      - "policies/cfmc_repeaters.yml"
      - "policies/ns9rc.yml"
      - "policies/sara_repeaters.yml"
      - "policies/ham_fm_simplex.yml"
      - "policies/ham_dmr_simplex.yml"
      - "policies/cook_public_safety.yml"
      - "policies/chicago_public_services.yml"
      - "policies/chicago_transit.yml"
      - "policies/tri_state_dmr.yml"
      - "policies/mmdvm_duplex_hotspot.yml"
