profile:
  name: "default"
  description: "Baseline build using common plans and local Chicago systems."
  include:
    paths:
      - "ssrf/plans/US/gmrs/*.yml"
      - "ssrf/plans/US/amateur/*.yml"
      - "ssrf/plans/US/murs/*.yml"
      - "ssrf/plans/US/marine/*.yml"
      - "ssrf/plans/US/business/*.yml"
      - "ssrf/plans/US/weather/*.yml"
      - "ssrf/plans/US/rail/*.yml"
      - "ssrf/systems/US/IL/Cook/Chicago/**/*.yml"
      - "ssrf/systems/US/IL/Cook/_Countywide/**/*.yml"
      - "ssrf/systems/US/IL/_Statewide/**/*.yml"
    services: [] # optional filter; empty means no filter
